public with sharing class indexHTML_1 {
    public indexHTML_1() {

        // <!DOCTYPE html>
        // <html lang="en">
        // <head>
        //     <meta charset="UTF-8">
        //     <meta http-equiv="X-UA-Compatible" content="IE=edge">
        //     <meta name="viewport" content="width=device-width, initial-scale=1.0">
        //     <link rel="stylesheet" href="style.css"/>
        //     <title>Build a Survey Form using HTML and CSS</title>
        // </head>
        // <body>
        //     <form id="form">
        //         <h1>SF Academy Survey Form</h1>
        //             <h3>About You</h3>
        //             <label for="name">Name</label>
        //             <input type="text" id="name" placeholder="Enter your name" required/>
        //             <label for="email">Email</label>
        //             <input type="email" id="email" placeholder="Enter your email" required/>
        //             <label for="batch">Batch</label>
        //             <input type="number" id="batch" placeholder="Enter your batch number" min="1" max="15" required/>
        //             <h3>Which career option best describes your intention to start this bootcamp?</h3>
        //             <select name="career" id="career">
        //                 <option value="admin">Salesforce Admin</option>
        //                 <option value="developer">Salesforce Developer</option>
        //                 <option value="cpq">Salesforce CPQ Specialist</option>
        //                 <option value="other">Other</option>
        //             </select>

        //             <h3>Would you recommend SF Academy to a friend?</h3>
        //             <input type="radio" id="recommend-yes" name="recommend"/>
        //             <label for="recommend-yes">Yes</label>
        //             <input type="radio" id="recommend-no" name="recommend"/>
        //             <label for="recommend-no">No</label>
        //             <input type="radio" id="recommend-maybe" name="recommend"/>
        //             <label for="recommend-maybe">Maybe</label>

        //             <h3>Languages and Frameworks known</h3>
        //             <input type="checkbox" id="javascript" value="javascript">
        //             <label for="javascript">Javascript</label><br>
        //             <input type="checkbox" id="apex" value="apex">
        //             <label for="apex">Apex</label><br>
        //             <input type="checkbox" id="lwc" value="lwc">
        //             <label for="lwc">LWC</label><br>
        //             <input type="checkbox" id="soql" value="soql">
        //             <label for="soql">SOQL</label><br>
        //             <input type="checkbox" id="cpq" value="cpq">
        //             <label for="cpq">CPQ</label><br>

        //             <h3>Any comments or suggestions</h3>
        //             <textarea placeholder="Enter your comment here"> </textarea>

        //         <button type="submit" value="submit">Submit</button>
        //     </form>
        // </body>
        // </html>

    }
}