public with sharing class styleCSS_1 {
    public styleCSS_1() {

        // body {
        //     background-color: #54BFA6;
        //     font-family: Verdana;
        
        // }
        
        // form {
        //     background-color: #fff;
        //     max-width: 500px;
        //     margin: 50px auto;
        //     padding: 30px 20px;
        //     box-shadow: 2px 5px 10px rgba(0, 0, 0, 0.5);
        // }
        
        // form label {
        //     display: inline-block;
        //     margin-bottom: 10px;
        //     margin-top:10px;
        // }
        
        // form input,
        // form select,
        // form textarea {
        //     border: 1px solid #777;
        //     border-radius: 2px;
        //     font-family: inherit;
        //     padding: 10px;
        //     display: block;
        //     width: 95%;
        // }
        
        // form input[type="radio"],
        // form input[type="checkbox"] {
        //     display: inline-block;
        //     width: auto;
        // }
        
        // button {
        //     background-color: #54BFA6;
        //     border: none;
        //     color:white;
        //     border-radius: 8px;
        //     font-size: 21px;
        //     width: 100%;
        //     margin: 50px 0 20px 0;
        //     padding:8px 0;
        // }
    }
}