public with sharing class indexHTML {
    public indexHTML() {

        // <!DOCTYPE html>
        // <html lang="en">
        
        // <head>
        //     <meta charset="UTF-8">
        //     <meta name="viewport" 
        //     content="width=device-width, initial-scale=1.0">
        //     <link rel="stylesheet" href="style.css">
        //     <title>Travel Blog</title>   
        // </head>
        
        // <body>
        //     <div class="header">
        //     <h1 id="title">My Travel Blog</h1>
        //     </div>
            //     <div class="row">
                //     <div class="city-card">
                //             <h3>London</h3>
                //             <img class="city-img" src="images/london.png" alt="london">
                //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
                //             <button>See Details</button>
                //     </div>
                //     <div class="city-card" >
                //             <h3>Bangkok</h3>
                //             <img class="city-img" src="images/bangkok.png" alt="bangkok">
                //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
                //             <button>See Details</button>
                //     </div>
                //     <div class="city-card" >
                //             <h3>Hong Kong</h3>
                //             <img class="city-img" src="images/hongkong.png" alt="london">
                //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
                //             <button>See Details</button>
                //     </div>

            //     </div>
        //     <div class="row">
        //             <div class="city-card" >
        //                 <h3>Istanbul</h3>
        //                 <img class="city-img" src="images/istanbul.png" alt="istanbul">
        //                 <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
        //                 <button>See Details</button>
        //         </div>
        //         <div class="city-card" >
        //             <h3>Madrid</h3>
        //             <img class="city-img" src="images/madrid.png" alt="madrid">
        //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
        //             <button>See Details</button>
        //         </div>
        //         <div class="city-card" >
        //             <h3>New York</h3>
        //             <img class="city-img" src="images/new-york.png" alt="new-york">
        //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
        //             <button>See Details</button>
        //         </div>
        //     </div>
        //     <div class="row">
        //         <div class="city-card" >
        //             <h3>Paris</h3>
        //             <img class="city-img" src="images/paris.png" alt="paris">
        //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
        //             <button>See Details</button>
        //     </div>
        //     <div class="city-card" >
        //             <h3>Tokyo</h3>
        //             <img class="city-img" src="images/tokyo.png" alt="tokyo">
        //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
        //             <button>See Details</button>
        //     </div>
        //     <div class="city-card" >
        //             <h3>Vienna</h3>
        //             <img class="city-img" src="images/vienna.png" alt="vienna">
        //             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ab, blanditiis veniam dolor recusandae nam quisquam earum cupiditate. Quia, voluptates?</p>
        //             <button>See Details</button>
        //     </div>

        //     </div>
        //     <div class="footer">
        //         <a href="https://www.facebook.com" target="_blank">
        //             <img class="icons" src="images/facebook.png" alt="facebook"/>
        //         </a>
        //         <a href="https://www.twitter.com" target="_blank">
        //             <img class="icons" src="images/twitter.png" alt="twitter"/>
        //         </a>
        //         <a href="https://www.instagram.com" target="_blank">
        //             <img class="icons" src="images/insta.png.webp" alt="instagram"/>
        //         </a>
        //     </div>
        // </body>
        // </html>

    }
}