public with sharing class styleCSS {
    public styleCSS() {
        // /* Resetting Default Browser Settings */
        // *{
        //     margin:0;
        //     padding:0;
        //     box-sizing:border-box;
        // }

        // /* Add your code below */

        // .header{
        //     text-align: center;
        //     background-color:#C1DCF4;
        //     padding-top:20px;
        //     padding-bottom:20px;
        // }
        // #title{
        //     color:orange;
        // }
        // .row{
        //     height:360px;
        //     margin-top:10px;
        //     padding-left:20px;
        //     padding-right:20px;
        // } 
        // .city-card{
        //     background-color: aliceblue;
        //     width:33%;
        //     text-align:center;
        //     padding:10px;
        //     display:inline-block;
        //     border-radius:8px;
            
        // }

        // .city-img{
        //     width:200px;
        //     height:200px;
        //     border-radius:8px;
        // }
        // button{
        //     background-color: orange;
        //     border:none;
        //     color:white;
        //     padding:8px 16px;
        //     margin-top:10px;
        //     border-radius:8px;
        //     cursor:pointer;
        // }
        // .footer{
        //     background-color:#C1DCF4;
        //     height:30px;
        //     text-align: center;
        //     margin-top:20px;

        // }
        // .icons{
        //     width:30px;
        // }

    }
}