public with sharing class QuickbooksConnector_Info {
    public QuickbooksConnector_Info() {

        // POST /oauth2/v1/tokens/bearer?grant_type
        //   =authorization_code&code
        //   =AB11707625089P4KLmuJkzAuOxmaW0XgKkcjRRaCUt7bxzSpYr&redirect
        //   _uri=https://developer.intuit.com/v2/OAuth2Playground
        //   /RedirectUrl
        // Content-Type: application/x-www-form-urlencoded
        // Accept: application/json
        // Authorization: Basic 
        //   QUJ5VlRXak1nN1Y3M1h1ZkVZR3lCdERQaGQzV0lkN3BXTWpMenIyMVRLRkJ0
        //   dmVWMEk6aWFKNnlHaXVBYzlTNnlKR2cwRVZKeUhDNXVhVWFMOGVGclBnOFZh
        //   Zw==






        // Status: 200
        // Connection: keep-alive
        // Keep-Alive: timeout=5
        // Strict-Transport-Security: max-age=15552000
        // Cache-Control: no-cache, no-store
        // Content-Type: application/json;charset=utf-8
        // Server: nginx
        // {
        // "refreshToken": 
        //      "AB11716351321MHWVq7SN6sNttMTGKtXHqsiBdnoAFnZ4oGllO",
        // "accessToken": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGly
        //      In0..hLwXCmZ9fsGFUMtHbuOE0w
        //      .TVZYJi1fkeOklEgKIHgv6E5PpTys9drcuxYnbntT41GB_9poN7EelBx
        //      nLVA6mmGvXqwujv5Vmnta1StDCeEcXHA5zkLUF3NSRK0toa0SqYg2WXk
        //      LkSgDYo15ueq_paax1v4e_c3zK
        //      -gSwSWp5akEPF0WsM6OmILMHKlnbbTrfSxSlJRi2XSnlOlVlykDn_d0E
        //      7OBPXyRcVC4q6EEEv8EtbC1xMcwvSEzR27JxKgZl8DcYCeDbNYUD5c69
        //      CYqk21etQNREA6VWnD4he3UGsyVx2c878H2jIbk2H08lE0eLYQLsZVRY
        //      xMC69KSECWwVn_SfyVmISAyWZxxIk0EZZCpFVHFnhlq3UlB5xJkCEEwv
        //      rV4OOHsASnKH5EByOYkbrtAYj2gXq3ZTLpNz7Yy8ssOnXTtRN8z3u0wZ
        //      yTYwyZt6nO5cJYqtT
        //      -yW4GzNtjfCVaaDYdx0VPW7kZNNlCxGWl5Xrn4fkhjFDFvJyIGyaueFv
        //      xlsEjRqVzToW5gUO76nJzUIr4sDNUkGLQ39hyES1Yvz3UOLN12Eaclrq
        //      GtSXLZXqUaWNyhGqDeBwGt_t1z4iMSYt
        //      -2g2bs80TLHqFLFOvCKhdRh4HMu4zRTokqzLTXzp101ngFpB7L_
        //      -QSA9Gp3NyQClFthV2xdAWQvFddHK5H8f1_0gpTjLe6CX0wns
        //      -TxnSZnAR6OZDB415pfqCyBBto2owpqc0lCjEnJyQRg_Zku5k4hHacUe
        //      fFMv9jYEjZFzyp-QMZpGkfDfkorprN_deq
        //      .YG8AUcuRfVYhI8hRZFpXGA",
        // "expires_in": 3600,
        // "x_refresh_token_expires_in": 8726400
        // }







        // Status: 200
        // Connection: keep-alive
        // Keep-Alive: timeout=5
        // Strict-Transport-Security: max-age=15552000
        // Cache-Control: no-cache, no-store
        // Content-Type: application/json;charset=utf-8
        // Server: nginx
        // {
        // "CompanyInfo": {
        // "CompanyName": "Advanced Sandbox Company_US_1",
        // "LegalName": "Advanced Sandbox Company_US_1",
        // "CompanyAddr": {
        // "Id": "1",
        // "Line1": "123 Sierra Way",
        // "City": "San Pablo",
        // "CountrySubDivisionCode": "CA",
        // "PostalCode": "87999",
        // "Lat": "36.6788345",
        // "Long": "-5.4464622"
        // },
        // "CustomerCommunicationAddr": {
        // "Id": "1",
        // "Line1": "123 Sierra Way",
        // "City": "San Pablo",
        // "CountrySubDivisionCode": "CA",
        // "PostalCode": "87999",
        // "Lat": "36.6788345",
        // "Long": "-5.4464622"
        // },
        // "LegalAddr": {
        // "Id": "1",
        // "Line1": "123 Sierra Way",
        // "City": "San Pablo",
        // "CountrySubDivisionCode": "CA",
        // "PostalCode": "87999",
        // "Lat": "36.6788345",
        // "Long": "-5.4464622"
        // },
        // "CustomerCommunicationEmailAddr": {
        // "Address": "noreply@quickbooks.com"
        // },
        // "PrimaryPhone": {},
        // "CompanyStartDate": "2024-02-08",
        // "FiscalYearStartMonth": "January",
        // "Country": "US",
        // "Email": {
        // "Address": "noreply@quickbooks.com"
        // },
        // "WebAddr": {},
        // "SupportedLanguages": "en",
        // "NameValue": [
        // {
        //     "Name": "NeoEnabled",
        //     "Value": "true"
        // },
        // {
        //     "Name": "IsQbdtMigrated",
        //     "Value": "false"
        // },
        // {
        //     "Name": "CompanyType",
        //     "Value": "Other"
        // },
        // {
        //     "Name": "SubscriptionStatus",
        //     "Value": "SUBSCRIBED"
        // },
        // {
        //     "Name": "OfferingSku",
        //     "Value": "QuickBooks Online Plus"
        // },
        // {
        //     "Name": "PayrollFeature",
        //     "Value": "false"
        // },
        // {
        //     "Name": "AccountantFeature",
        //     "Value": "false"
        // },
        // {
        //     "Name": "QBOIndustryType",
        //     "Value": "Landscaping Services"
        // },
        // {
        //     "Name": "ItemCategoriesFeature",
        //     "Value": "true"
        // },
        // {
        //     "Name": "AssignedTime",
        //     "Value": "2024-02-08T08:02:39-08:00"
        // }
        // ],
        // "domain": "QBO",
        // "sparse": false,
        // "Id": "1",
        // "SyncToken": "9",
        // "MetaData": {
        // "CreateTime": "2024-02-08T07:02:38-08:00",
        // "LastUpdatedTime": "2024-02-08T07:03:21-08:00"
        // }
        // },
        // "time": "2024-02-10T20:41:34.273-08:00"
        // }
    }
}